name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Fazer build
        run: echo "Fazendo build"

  generate:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      output1: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Setar variável
        id: set-version
        run: echo "version=1.2" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Recuperar versão e usar output do job anterior
        run: echo "teste de recuperação de versão ${{needs.generate.outputs.output1}}"

