name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v4
      
      - name: instalar java 17
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: fazer build
        run: echo "Fazendo build"

  generate:
    runs-on: ubuntu-latest
    needs: build
    
    outputs:
      output1: ${{ steps.set-version.outputs.version }}
    steps:
      - name: setar variavel
      - id: set-version
        run: echo "::set-output name=version::1.2"

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: recuperar versao
      - id: get-version
        run: echo "recuperando variavel"
      
      
        
      
